# Generated by Django 3.2.24 on 2024-02-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('teacher', models.BooleanField(default=False)),
                ('Mathematics', models.IntegerField()),
                ('English', models.IntegerField()),
                ('Physics', models.IntegerField()),
                ('Biology', models.IntegerField()),
                ('History', models.IntegerField()),
                ('Geography', models.IntegerField()),
                ('Business', models.IntegerField()),
            ],
        ),
    ]
